<a href="https://colab.research.google.com/github/samarjithMnagesha/pytorch/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

# *List*

In [6]:
List_1=torch.randn(3,4)
print(List_1)

tensor([[ 0.0280, -0.5834, -0.3168,  0.2339],
        [-0.3364, -0.1033,  0.1292,  1.5101],
        [-0.4454,  1.1277,  0.3408, -1.5530]])


In [9]:
List_1.dtype

torch.float32

Converting numpy array to tensor

In [10]:
arr=np.random.randn(3,4)

In [11]:
arr

array([[ 0.45772569,  0.26032613, -1.05222679,  0.13787572],
       [-0.06523781, -1.81460874,  0.49706373, -1.1981835 ],
       [-0.42424318,  0.34524748, -1.22554074,  0.52884771]])

In [12]:
np_to_torch=torch.tensor(arr)

In [13]:
np_to_torch

tensor([[ 0.4577,  0.2603, -1.0522,  0.1379],
        [-0.0652, -1.8146,  0.4971, -1.1982],
        [-0.4242,  0.3452, -1.2255,  0.5288]], dtype=torch.float64)